[workspace]
members = ["relget", "xtask"]
default-members = ["relget"]
resolver = "3"

[workspace.lints.rust]
future-incompatible = "warn"
nonstandard-style = "deny"

[workspace.lints.clippy]
uninlined_format_args = "warn"
map_unwrap_or = "warn"
unnecessary_wraps = "warn"

[workspace.metadata.release]
publish = false
push = false
shared-version = "relget"
tag-name = "v{{version}}"
pre-release-commit-message = "build: bumped version to v{{version}}"
tag-message = ""

[[workspace.metadata.release.pre-release-replacements]]
file = "../CHANGELOG.md"
search = "## unreleased"
replace = "## unreleased\n\n## v{{version}} ({{date}})"
exactly = 1
